import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Footer, Navbar } from "./components";
import "./globals.css";
import "./main.scss";

const montserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invicta Kent",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // or PNG: "/favicon.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
